<center>
    <H1> NAIVE BAYES CLASSIFIER </H1>
    <br>
======================================================================================================================
<br>
Naive Bayes Classification algorithm is a type of supervised machine learning algorithm. It is extremely easy to implement in its most basic form, and yet performs quite complex classification tasks.


## STEP 1: IMPORT LIBRARIES

In [1]:
!pip install pandas
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split 
from sklearn.metrics import confusion_matrix, accuracy_score


[notice] A new release of pip available: 22.2.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip


## STEP 2: LOAD DATASET

In [2]:
dataset = pd.read_csv('C:/Users/NIKHIL/Desktop/twitterf-main/data/twitter_dataset.csv', encoding = 'latin-1')  #load data from csv
dataset.head()                  #show first 5 rows

name_wt  statuses_count  followers_count  friends_count  favourites_count  \
0  0.600000             195               19             53                58   
1  0.705882               9               67            555                 2   
2  0.916667              20               21            267                 0   
3  0.500000              28               16            325                 0   
4  0.733333              45               20            515                 0   

   listed_count  label  
0             0      0  
1             1      0  
2             0      1  
3             0      1  
4             0      1

In [3]:
dataset.shape

(2818, 7)

## STEP 3: FEATURE SELECTION

In [4]:
features=[]
for attributes in dataset.columns:
    if attributes != 'label':
        features.append(attributes)
features

['name_wt',
 'statuses_count',
 'followers_count',
 'friends_count',
 'favourites_count',
 'listed_count']

In [5]:
data = dataset.values
data

array([[6.00000000e-01, 1.95000000e+02, 1.90000000e+01, ...,
        5.80000000e+01, 0.00000000e+00, 0.00000000e+00],
       [7.05882353e-01, 9.00000000e+00, 6.70000000e+01, ...,
        2.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [9.16666667e-01, 2.00000000e+01, 2.10000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       ...,
       [8.33333333e-01, 1.73000000e+03, 3.81000000e+02, ...,
        2.18000000e+02, 0.00000000e+00, 0.00000000e+00],
       [8.82352941e-01, 1.53650000e+04, 3.81300000e+03, ...,
        5.50000000e+02, 6.30000000e+01, 0.00000000e+00],
       [9.33333333e-01, 3.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [6]:
print("Total instances : ", data.shape[0], "\nNumber of features : ", data.shape[1])

Total instances :  2818 
Number of features :  7


In [7]:
#convert label column into 1D arrray

label = np.array(dataset['label'])
# label

## STEP 4: CREATE TEST AND TRAIN SETS

We will randomly split our dataset in 80–20 ratio. Where 80% of the total data will be used as training set and rest 20% will be considered as test set. 

In [8]:
'''
    We have X_train, y_train, X_test, y_test.
    Using these lists and dataframes we will randomly create two non-overlapping datasets 
        1. training set
        2. testing set
'''

X_train, X_test, y_train, y_test = train_test_split(data, label, test_size=0.2, random_state=0)

print("Number of training instances: ", X_train.shape[0])
print("Number of testing instances: ", X_test.shape[0])

Number of training instances:  2254
Number of testing instances:  564


## STEP 5: TRAIN THE CLASSIFIER 

In [9]:
# Generate the model
nb_model = GaussianNB()

# Train the model using the training sets
data = X_train
label = y_train

nb_model.fit(data, label)

GaussianNB()

## STEP 6: TEST THE CLASSIFIER 

Now our model is ready. We will test our data against given labels. For every test case, calculate class score (using Bayes theorem) and assign the class to the test case, having maximum score.

In [10]:
#test set
X_test

array([[9.00000000e-01, 2.90000000e+01, 1.20000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.21052632e-01, 6.55000000e+02, 3.20000000e+01, ...,
        5.40000000e+01, 0.00000000e+00, 0.00000000e+00],
       [4.37500000e-01, 5.50000000e+01, 2.00000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       ...,
       [9.23076923e-01, 3.70000000e+01, 2.00000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [7.50000000e-01, 2.90000000e+01, 1.70000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.54545455e-01, 6.50000000e+01, 1.90000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [11]:
nb_model.predict([X_test[1]])    #testing for single instance

array([0], dtype=int64)

In [12]:
'''
   Now, apply the model to the entire test set and predict the label for each test example

'''       
       
y_predict = []                       #to store prediction of each test example

for test_case in range(len(X_test)): 
    label = nb_model.predict([X_test[test_case]])
    
    #append to the predictions list
    y_predict.append(label.item())

#predictions

In [13]:
y_predict   #predicted labels for al the test instances

[1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,


## STEP 7: EVALUATION OF CLASSIFICATION RESULTS

The classifier will be evaluted using Accuracy, Recall, Precision and F-measure. For this first, a confusion matrix will be created. 

In [14]:
#true negatives is C(0,0), false negatives is C(1,0), false positives is C(0,1) and true positives is C(1,1) 
conf_matrix = confusion_matrix(y_test, y_predict)

In [15]:
#true_negative
TN = conf_matrix[0][0]
#false_negative
FN = conf_matrix[1][0]
#false_positive
FP = conf_matrix[0][1]
#true_positive
TP = conf_matrix[1][1]

In [16]:
# Recall is the ratio of the total number of correctly classified positive examples divided by the total number of positive examples. 
# High Recall indicates the class is correctly recognized (small number of FN)

recall = (TP)/(TP + FN)

In [17]:
# Precision is the the total number of correctly classified positive examples divided by the total number of predicted positive examples. 
# High Precision indicates an example labeled as positive is indeed positive (small number of FP)

precision = (TP)/(TP + FP)

In [18]:
fmeasure = (2*recall*precision)/(recall+precision)   #f-measure is the harmonice mean of Recall and Precision
accuracy = (TP + TN)/(TN + FN + FP + TP) #Total number of correct predictions divided by total number of instances predicted
ErrorRate=(FP+FN)/(TN + FN + FP + TP)
accuracy_score(y_test, y_predict)

0.875886524822695

In [19]:
print("------ CLASSIFICATION PERFORMANCE OF THE NAIVE BAYES MODEL ------ \n"\
      "\n Recall : ", (recall*100) ,"%" \
      "\n Precision : ", (precision*100) ,"%" \
      "\n Accuracy : ", (accuracy*100) ,"%" \
      "\n F-measure : ", (fmeasure*100) ,"%" 
      "\n ErrorRate : ", (ErrorRate*100) ,"%" )


------ CLASSIFICATION PERFORMANCE OF THE NAIVE BAYES MODEL ------ 

 Recall :  98.56630824372759 %
 Precision :  80.64516129032258 %
 Accuracy :  87.58865248226951 %
 F-measure :  88.70967741935483 %
 ErrorRate :  12.411347517730496 %
